parameters:
    tremend_krumo.krumo.class: Krumo
    tremend_krumo.krumo.file: %kernel.root_dir%/../vendor/bundles/Tremend/KrumoBundle/Krumo/Krumo.php

services:
    tremend_krumo.krumo:
        class: %tremend_krumo.krumo.class%
        file: %tremend_krumo.krumo.file%
        arguments: [@kernel]
    krumo:
        alias: tremend_krumo.krumo
